### ISSUE TITLE
Concat dependency

### ISSUE THREAD

**Issue by throwaway99** [gds-operations/puppet-auditd#38]
Hi,

I'm using librarian puppet and am getting a conflict between the dependencies of this module and other modules in use.

The dependency is:-

{ "name": "puppetlabs/concat", "version_requirement": ">=1.0.0 <=1.2.1" }

and I have some other modules requiring concat >=1.2.5.

I'm off to test locally but is there really a hard requirement on this version of concat?

Thanks.

**Comment by rjw1** [comment]
Hopefully not but we do seem to have a good reason in https://github.com/gds-operations/puppet-auditd/commit/9a6d8cac16541d35ce23d2f190d213e54685122f

We would welcome a PR which bumped it though.

**Comment by throwaway99** [comment]
I'm not much of a coder but I've had a go.

**Comment by throwaway99** [comment]
Hi,

Sorry to be a pain but any chance you could have a quick look at the MR?

Thanks.

**Comment by deanwilson** [comment]
This is hopefully fixed in master now that #39 has been merged so I'm going to close this issue. Thank you for raising the problem and (especially) the PR to fix it.
